version: '3'
services:
  jupyter:
    user: "root"
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work
      - ./parquet:/home/jovyan/parquet
    command: "start-notebook.py --IdentityProvider.token=${JUPYTER_TOKEN}"
    environment:
      CHOWN_EXTRA: "/home/jovyan"
      CHOWN_EXTRA_OPTS: "-R"