include:
  - spark_airflow/docker-compose.yml
services:
  jupyter:
    user: "root"
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.jupyter
    container_name: jupyter
    restart: unless-stopped
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./work:/home/jovyan/work
      - ./parquet:/home/jovyan/parquet
    command: "start-notebook.py --IdentityProvider.token=${JUPYTER_TOKEN}"
    environment:
      CHOWN_EXTRA: "/home/jovyan"
      CHOWN_EXTRA_OPTS: "-R"

  dw:
    image: postgres:15-alpine
    container_name: dw
    restart: unless-stopped
    ports:
        - "55555:5432"
    volumes:
        - ./postgres_dw:/var/lib/postgresql/data
        - ./pg/postgres/seeds:/docker-entrypoint-initdb.d
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres